name: Publish to PYPI

on:
    workflow_run:
        workflows: [Test package]
        types: [completed]
        branches: release

permissions:
    contents: read

jobs:
    release-build:
        name: Create build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: build release distributions
              run: |
                  pip install poetry
                  poetry build

            - name: upload dists
              uses: actions/upload-artifact@v4
              with:
                  name: release-dists
                  path: dist/

    pypi-publish:
        name: Release
        runs-on: ubuntu-latest
        needs:
            - release-build
        permissions:
            id-token: write

        steps:
            - name: Retrieve release distributions
              uses: actions/download-artifact@v4
              with:
                  name: release-dists
                  path: dist/

            - name: Publish release distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
